Repository PlutoLang/Pluto, pull requests merged in 2022-06, with the labels that each got.

#1 Merge compile-time warnings for duplicate local declarations into main
  README.md
  src/lparser.c
  src/lparser.h
  src/lua.c
  src/luaconf.h
Labels: enhancement

#2 Merge improved-compile-errors into main.
  README.md
  src/llex.c
  src/llex.h
  src/lparser.c
  src/lparser.h
  src/luaconf.h
Labels: enhancement

#4 Support for ANSI color sequences in various error & warning messages.
  README.md
  src/lparser.c
  src/lparser.h
  src/luaconf.h
Labels: enhancement

#5 Support for ternary expressions.
  README.md
  src/lcode.c
  src/lcode.h
  src/lparser.c
Labels: enhancement

#6 Implementation of continue statement.
  .gitignore
  README.md
  src/llex.c
  src/llex.h
  src/lparser.c
  src/luaconf.h
  tests/augmented_assignment.lua
Labels: enhancement

#8 Increase local variable limit
  src/lparser.cpp
Labels: enhancement

#12 Set up for compiling with Visual Studio & fix associated warnings
  .gitignore
  Pluto.sln
  Pluto.vcxproj
  Pluto.vcxproj.filters
  Pluto.vcxproj.user
  src/lobject.h
  src/luaconf.h
Labels: qol improvement

#11 [Optimization] Cache table length, 2x speedup.
  README.md
  src/lapi.cpp
  src/lobject.h
  src/ltablib.cpp
  src/lua.h
  src/lvm.cpp
  tests/lenbench.lua
  tests/lentest.lua
Labels: enhancement

#13 Fix dangling pointers
  src/lparser.cpp
Labels: bugfix

#14 Update error functions to be [[noreturn]]
  src/lapi.cpp
  src/lauxlib.cpp
  src/lauxlib.h
  src/lbaselib.cpp
  src/lcode.cpp
  src/lcode.h
  src/lcorolib.cpp
  src/ldblib.cpp
  src/ldebug.cpp
  src/ldebug.h
  src/ldo.cpp
  src/ldo.h
  src/liolib.cpp
  src/llex.cpp
  src/llex.h
  src/llimits.h
  src/lmathlib.cpp
  src/lmem.cpp
  src/lmem.h
  src/loadlib.cpp
  src/loslib.cpp
  src/lparser.cpp
  src/lstrlib.cpp
  src/ltablib.cpp
  src/lua.cpp
  src/lua.h
  src/lundump.cpp
  src/lutf8lib.cpp
Labels: improvement

#17 [New Feature] Table Freezing / Immutability
  README.md
  src/lapi.cpp
  src/lbaselib.cpp
  src/ldebug.cpp
  src/lobject.h
  src/ltable.cpp
  src/ltablib.cpp
  src/lua.h
  src/lvm.cpp
  tests/basic.lua
Labels: enhancement

#18 [New Feature] Switch/Case statements.
  README.md
  src/llex.cpp
  src/llex.h
  src/lparser.cpp
  tests/basic.lua
Labels: enhancement
