Repository PlutoLang/Pluto, pull requests merged in 2022-07, with the labels that each got.

#23 Add user_data to global_State
  src/lstate.h
Labels: enhancement

#25 Add !=
  README.md
  src/llex.cpp
Labels: enhancement

#32 Fix more UB regarding frozen tables.
  src/lvm.cpp
Labels: improvement

#34 Add "try it yourself!" links for most features
  README.md
Labels: enhancement

#37 Add new time functions to os api
  README.md
  src/loslib.cpp
Labels: enhancement

#38 Add negative string indexing
  README.md
  src/lvm.cpp
  tests/basic.lua
Labels: enhancement

#39 Compound concatenation operator.
  README.md
  src/llex.cpp
  src/llex.h
  src/lparser.cpp
  tests/compat.lua
Labels: enhancement, help wanted

#41 Fix ILP with REPEAT UNTIL loops.
  src/lvm.cpp
Labels: bugfix

#46 Fix inaccurate instruction counter on some instructions.
  src/lvm.cpp
Labels: bugfix

#54 Fix jank with Windows build on Github Actions
  .github/workflows/all.yml
  scripts/common.php
  scripts/compile.php
  scripts/link_pluto.php
  scripts/link_plutoc.php
  scripts/link_shared.php
  scripts/link_static.php
Labels: improvement

#57 REPEAT .. WHEN loop support
  src/llex.cpp
  src/llex.h
  src/lparser.cpp
  src/lparser.h
Labels: enhancement

#55 Optional parentheses around string literals for method invocation.
  src/lparser.cpp
Labels: enhancement

#58 Expand standard IO library.
  src/liolib.cpp
Labels: enhancement

#59 Granual compatibility mode
  src/llex.cpp
  src/llex.h
  src/lparser.cpp
  src/lparser.h
  src/luaconf.h
Labels: improvement

#62 Add _PVERSION, assert copyright in compiled executable, bump version to 0.2.0
  src/lbaselib.cpp
  src/lua.cpp
  src/lua.h
Labels: enhancement

#67 Fix continue statement again.
  src/lparser.cpp
  src/lua.h
  tests/basic.lua
Labels: bugfix

#83 0.3.0: Implement `break N` syntax support.
  src/lparser.cpp
  tests/basic.lua
Labels: enhancement
